vim.keymap.set("n", "<leader>w", ":w<CR>", { silent = false })
vim.keymap.set("n", "<leader>q", ":q<CR>", { silent = false })
vim.keymap.set("n", "<leader>ff", "<cmd>Telescope find_files<CR>", { silent = false })
vim.keymap.set("n", "<leader>fg", "<cmd>Telescope live_grep<CR>", { silent = false })
vim.keymap.set("n", "<leader>fb", "<cmd>Telescope buffers<CR>", { silent = false })
vim.keymap.set("n", "<leader>fh", "<cmd>Telescope help_tags<CR>", { silent = false })
vim.keymap.set("n", "<leader>lp", function()
  require("gitsigns").preview_hunk()
end, { silent = false })
vim.keymap.set("n", "<leader>lg", "<cmd>LazyGit<CR>", { silent = false })
